public enum MenuOptions {
    ADD_STUDENT,
    ADD_MODULE,
    ENROLL_STUDENT,
    ADD_MARK,
    VIEW_ALL_RECORDS,
    VIEW_STUDENT_RECORD,
    CALCULATE_FINAL_MARK,
    CALCULATE_AVERAGE,
    EXIT
}
